# Generated by Django 5.0.6 on 2024-09-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_age', models.IntegerField(default=18)),
                ('user_category', models.CharField(max_length=50)),
                ('user_state', models.CharField(blank=True, max_length=100, null=True)),
                ('user_annualincome', models.CharField(blank=True, max_length=100, null=True)),
                ('user_profession', models.CharField(blank=True, max_length=100, null=True)),
                ('user_gender', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['user_name'],
            },
        ),
    ]
