# Generated by Django 5.0.6 on 2024-09-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=100)),
                ('scheme_caste', models.CharField(max_length=100)),
                ('scheme_annualIncome', models.IntegerField()),
                ('scheme_gender', models.CharField(default='All', max_length=100)),
                ('scheme_age', models.IntegerField(default=1)),
                ('scheme_Minage', models.IntegerField(default=1)),
                ('scheme_education_level', models.CharField(default='NAN', max_length=100)),
                ('scheme_benifits', models.TextField(default='NAN')),
            ],
            options={
                'ordering': ['scheme_name'],
            },
        ),
    ]
