# Generated by Django 5.0.6 on 2024-09-01 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_scheme_benifits_schemedata_scheme_benefits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schemedata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userdata',
            options={},
        ),
    ]
